# 🧠 01: Array Basics & Creation (Exercises 01–15)

**Challenger:** Mohammed Jabir • **Challenge:** 100 NumPy Exercises

> **💡 How to Practice:** 
> 1. Write your own code in the empty code cell below each problem.
> 2. Try solving without looking at hints first.
> 3. If you get stuck, click the **💡 Hint** dropdown for guidance without spoiling the answer.
> 4. Execute your code with `Shift + Enter` and verify with the expected output.
> 5. Keep your code saved here as your personal learning portfolio!

---


### Exercise 01: Import numpy as np and print the version
**Difficulty:** `★☆☆`  
**Tags:** `Basics`

Import the numpy library under the standard alias `np` and print its version string.

**Expected Output:**
`A version string such as '2.x.x'`

<details>
<summary>💡 Hint</summary>

Use `import numpy as np` and inspect `np.__version__`.

</details>


In [2]:
# Exercise 01: Import numpy as np and print the version
# Write your solution below:

import numpy as np

print(np.__version__)

2.4.3


### Exercise 02: Print numpy configuration and build info
**Difficulty:** `★☆☆`  
**Tags:** `Basics, Environment`

Display NumPy's build configuration to check linear algebra libraries and compiler options.

**Expected Output:**
`NumPy build configuration output`

<details>
<summary>💡 Hint</summary>

Check `np.show_config()`.

</details>


In [3]:
# Exercise 02: Print numpy configuration and build info
# Write your solution below:

np.show_config()


Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0q_f6wui/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0q_f6wui/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.31.dev  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.31.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0q_f6wui/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0q_f6wui/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configurat

### Exercise 03: Create a null vector of size 10
**Difficulty:** `★☆☆`  
**Tags:** `Array Creation`

Create a 1D NumPy array of size 10 containing all zeros.

**Expected Output:**
`[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]`

<details>
<summary>💡 Hint</summary>

Use `np.zeros(10)`.

</details>


In [5]:
# Exercise 03: Create a null vector of size 10
# Write your solution below:

arr = np.zeros(10)

print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Exercise 04: Find the memory size of any array
**Difficulty:** `★☆☆`  
**Tags:** `Memory, Attributes`

Create any array and calculate the total memory size in bytes occupied by its data buffer.

**Expected Output:**
`Total bytes as integer`

<details>
<summary>💡 Hint</summary>

Check the `nbytes` attribute, or multiply `size` by `itemsize`.

</details>


In [38]:
# Exercise 04: Find the memory size of any array
# Write your solution below:

arr = np.array([1, 2, 3, 4, 5])  # Here, default array element type is "int64". One element takes 8 bytes.

print(arr.nbytes)

arr2 = np.array([1, 2, 3, 4, 5], dtype="int32")  # One element takes 4 bytes.

print(arr2.size * arr2.itemsize)  # Instead of nbytes we can use this

40
20


### Exercise 05: Get documentation of numpy add function from code
**Difficulty:** `★☆☆`  
**Tags:** `Documentation`

Print the inline documentation/help for the `np.add` function.

**Expected Output:**
`Docstring information for add`

<details>
<summary>💡 Hint</summary>

Use `np.info(np.add)` or `help(np.add)`.

</details>


In [41]:
# Exercise 05: Get documentation of numpy add function from code
# Write your solution below:

np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [46]:
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

### Exercise 06: Create a null vector of size 10 but fifth value is 1
**Difficulty:** `★☆☆`  
**Tags:** `Indexing`

Create a vector of 10 zeros, then set the fifth element (index 4) to 1.

**Expected Output:**
`[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]`

<details>
<summary>💡 Hint</summary>

Initialize with `np.zeros(10)` and assign to index `[4]`.

</details>


In [47]:
# Exercise 06: Create a null vector of size 10 but fifth value is 1
# Write your solution below:

null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Exercise 07: Create a vector with values ranging from 10 to 49
**Difficulty:** `★☆☆`  
**Tags:** `Array Creation`

Generate a 1D array containing integers starting from 10 up to and including 49.

**Expected Output:**
`[10 11 12 ... 47 48 49] (length 40)`

<details>
<summary>💡 Hint</summary>

Use `np.arange(start, stop)`. Remember the stop value is exclusive!

</details>


In [67]:
# Exercise 07: Create a vector with values ranging from 10 to 49
# Write your solution below:

arr = np.arange(10, 50)

print(arr)
print(f"\nLength: {len(arr)}")

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Length: 40


### Exercise 08: Reverse a vector (first element becomes last)
**Difficulty:** `★☆☆`  
**Tags:** `Slicing`

Given a vector `Z = np.arange(10)`, reverse it so the elements are in descending order.

**Expected Output:**
`[9 8 7 6 5 4 3 2 1 0]`

<details>
<summary>💡 Hint</summary>

Try negative step slicing `Z[::-1]` or `np.flip(Z)`.

</details>


In [75]:
# Exercise 08: Reverse a vector (first element becomes last)
# Write your solution below:

arr = np.arange(10)

print(arr[::-1])


[9 8 7 6 5 4 3 2 1 0]


In [ ]:
arr2 = np.arange(10)

print(np.flip(arr2))

[9 8 7 6 5 4 3 2 1 0]


### Exercise 09: Create a 3x3 matrix with values ranging from 0 to 8
**Difficulty:** `★☆☆`  
**Tags:** `Reshaping`

Create an array with values from 0 to 8, and reshape it into a 3x3 2D matrix.

**Expected Output:**
`[[0 1 2]
 [3 4 5]
 [6 7 8]]`

<details>
<summary>💡 Hint</summary>

Combine `np.arange(9)` with `.reshape(3, 3)`.

</details>


In [95]:
# Exercise 09: Create a 3x3 matrix with values ranging from 0 to 8
# Write your solution below:

arr = np.arange(9).reshape(3,3)

print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Exercise 10: Find indices of non-zero elements from [1,2,0,0,4,0]
**Difficulty:** `★☆☆`  
**Tags:** `Searching`

Given array `[1, 2, 0, 0, 4, 0]`, find the indices of elements that are not zero.

**Expected Output:**
`array([0, 1, 4])`

<details>
<summary>💡 Hint</summary>

Use `np.nonzero(...)`.

</details>


In [101]:
# Exercise 10: Find indices of non-zero elements from [1,2,0,0,4,0]
# Write your solution below:

arr = np.array([1, 2, 0, 0, 4, 0])

print(np.nonzero(arr))

(array([0, 1, 4]),)


### Exercise 11: Create a 3x3 identity matrix
**Difficulty:** `★☆☆`  
**Tags:** `Linear Algebra`

Create a 3x3 2D array with ones on the main diagonal and zeros everywhere else.

**Expected Output:**
`3x3 identity matrix`

<details>
<summary>💡 Hint</summary>

Use `np.eye(3)`.

</details>


In [115]:
# Exercise 11: Create a 3x3 identity matrix
# Write your solution below:

arr = np.eye(3)

print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Exercise 12: Create a 3x3x3 array with random values
**Difficulty:** `★☆☆`  
**Tags:** `Random`

Generate a 3-dimensional array of shape (3, 3, 3) filled with uniform random values in [0, 1).

**Expected Output:**
`3x3x3 array of random floats`

<details>
<summary>💡 Hint</summary>

Use modern generator `np.random.default_rng().random((3, 3, 3))`.

</details>


In [123]:
# Exercise 12: Create a 3x3x3 array with random values
# Write your solution below:

rand_arr = np.random.default_rng().random((3, 3, 3))

print(rand_arr)


[[[0.58140671 0.96827398 0.91718275]
  [0.34713166 0.66940657 0.13432983]
  [0.82154947 0.93946285 0.13694907]]

 [[0.34269854 0.16967494 0.10219012]
  [0.71248167 0.1770211  0.25251863]
  [0.63704847 0.5260379  0.8010533 ]]

 [[0.06635951 0.4911679  0.73860572]
  [0.3694816  0.01869176 0.49074688]
  [0.54261369 0.85540932 0.62175617]]]


### Exercise 13: Create a 10x10 array with random values and find min and max
**Difficulty:** `★☆☆`  
**Tags:** `Statistics`

Generate a 10x10 array of random numbers, and print its minimum and maximum values.

**Expected Output:**
`Minimum and maximum float values`

<details>
<summary>💡 Hint</summary>

Call `.min()` and `.max()` methods on your random array.

</details>


In [129]:
# Exercise 13: Create a 10x10 array with random values and find min and max
# Write your solution below:

rand_arr = np.random.default_rng().random((10, 10))
print(rand_arr)


print(f"\nMinimum value: {np.min(rand_arr)}\nMaximum Value: {rand_arr.max()}")


[[0.61942957 0.02025551 0.23349155 0.29037821 0.32538225 0.64327754
  0.35034128 0.76139235 0.87416538 0.84991445]
 [0.10740223 0.31510625 0.092067   0.23210307 0.91538181 0.11953817
  0.25421665 0.47622524 0.26363737 0.54401285]
 [0.79349338 0.92483294 0.96999163 0.93010539 0.74634451 0.93707885
  0.14082832 0.58287756 0.79311336 0.6704567 ]
 [0.30650428 0.84811742 0.74586795 0.48694699 0.77189307 0.24987204
  0.03975998 0.9134528  0.44450463 0.288777  ]
 [0.00109704 0.37441636 0.08854645 0.67563822 0.42248915 0.93121641
  0.80583168 0.66814252 0.44907363 0.30429247]
 [0.39447348 0.50947837 0.63485819 0.00910236 0.07939965 0.69968594
  0.70846541 0.79652547 0.43052843 0.25637466]
 [0.34835382 0.51693497 0.84031375 0.40407678 0.76728134 0.15851667
  0.00434734 0.05484633 0.79491601 0.49777804]
 [0.96268133 0.02532645 0.50710474 0.40996831 0.87003603 0.31919538
  0.49249439 0.16910055 0.45412858 0.05998233]
 [0.17406991 0.14690664 0.04181719 0.81444192 0.44749794 0.6713193
  0.84085792 

### Exercise 14: Create a random vector of size 30 and find the mean value
**Difficulty:** `★☆☆`  
**Tags:** `Statistics`

Generate a random 1D vector of 30 elements and calculate its arithmetic mean.

**Expected Output:**
`Mean value close to 0.5`

<details>
<summary>💡 Hint</summary>

Call `.mean()` on the vector.

</details>


In [136]:
# Exercise 14: Create a random vector of size 30 and find the mean value
# Write your solution below:

rand_arr = np.random.default_rng().random(30).mean()

print(rand_arr)


0.5278507398805506


### Exercise 15: Create a 2D array with 1 on the border and 0 inside
**Difficulty:** `★☆☆`  
**Tags:** `Slicing`

Create an array of ones (e.g. shape 6x6), then set the inner elements (excluding outer rows & columns) to 0.

**Expected Output:**
`Matrix with border 1s and interior 0s`

<details>
<summary>💡 Hint</summary>

Use slicing: `Z[1:-1, 1:-1] = 0`.

</details>


In [160]:
# Exercise 15: Create a 2D array with 1 on the border and 0 inside
# Write your solution below:

ones_arr = np.ones((6, 6), dtype=int)

ones_arr[1:-1, 1:-1] = 0

print(ones_arr)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]
