# 🧠 03: Math, Statistics & Broadcasting (Exercises 31–45)

**Challenger:** Mohammed Jabir • **Challenge:** 100 NumPy Exercises

> **💡 How to Practice:** 
> 1. Write your own code in the empty code cell below each problem.
> 2. Try solving without looking at hints first.
> 3. If you get stuck, click the **💡 Hint** dropdown for guidance without spoiling the answer.
> 4. Execute your code with `Shift + Enter` and verify with the expected output.
> 5. Keep your code saved here as your personal learning portfolio!

---


In [2]:
import numpy as np
print(f"NumPy version: {np.__version__}")

NumPy version: 2.4.3


### Exercise 31: How to ignore all numpy warnings?
**Difficulty:** `★☆☆`  
**Tags:** `Warnings`

Execute an operation that would normally produce a warning (e.g. 1/0) inside a context where warnings are ignored.

**Expected Output:**
`Clean execution without console warnings`

<details>
<summary>💡 Hint</summary>

Use `with np.errstate(all='ignore'):`.

</details>


In [3]:
# Exercise 31: How to ignore all numpy warnings?
# Write your solution below:

with np.errstate(all='ignore'):
    print(np.ones(1) / 0)

[inf]


### Exercise 32: Is the following expression true? np.sqrt(-1) == np.emath.sqrt(-1)
**Difficulty:** `★☆☆`  
**Tags:** `Math`

Evaluate `np.sqrt(-1) == np.emath.sqrt(-1)` and explain why.

**Expected Output:**
`False`

<details>
<summary>💡 Hint</summary>

`np.sqrt(-1)` produces `nan`. `np.emath.sqrt(-1)` produces `1j`. Is `nan == 1j`?

</details>


In [4]:
# Exercise 32: Is the following expression true? np.sqrt(-1) == np.emath.sqrt(-1)
# Write your solution below:

print(np.sqrt(-1))  # 1. Standard sqrt on a negative number returns NaN (Not a Number)
print(np.emath.sqrt(-1))  # 2. emath.sqrt supports complex numbers and returns 1j

# 3. Comparing NaN with a complex number gives False
print(np.sqrt(-1) == np.emath.sqrt(-1))

nan
1j
False


C:\Users\jabir\AppData\Local\Temp\ipykernel_21612\4053166918.py:4: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))  # 1. Standard sqrt on a negative number returns NaN (Not a Number)
C:\Users\jabir\AppData\Local\Temp\ipykernel_21612\4053166918.py:8: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


### Exercise 33: How to get the dates of yesterday, today and tomorrow?
**Difficulty:** `★☆☆`  
**Tags:** `Datetime`

Use `np.datetime64` and `np.timedelta64` to compute yesterday, today, and tomorrow's date.

**Expected Output:**
`Three datetime64 objects`

<details>
<summary>💡 Hint</summary>

`today = np.datetime64('today', 'D')`. Add/subtract `np.timedelta64(1, 'D')`.

</details>


In [5]:
# Exercise 33: How to get the dates of yesterday, today and tomorrow?
# Write your solution below:

today = np.datetime64('2026-10-01')

print("Yesterday date: ", today - np.timedelta64(1, 'D'))
print("Today date: ", today)
print("Tomorrow data: ", today + np.timedelta64(1, 'D'))


Yesterday date:  2026-09-30
Today date:  2026-10-01
Tomorrow data:  2026-10-02


### Exercise 34: How to get all dates corresponding to the month of July 2016?
**Difficulty:** `★★☆`  
**Tags:** `Datetime`

Generate an array containing every calendar day from 2016-07-01 to 2016-07-31.

**Expected Output:**
`Array of 31 dates`

<details>
<summary>💡 Hint</summary>

Use `np.arange('2016-07', '2016-08', dtype='datetime64[D]')`.

</details>


In [6]:
# Exercise 34: How to get all dates corresponding to the month of July 2016?
# Write your solution below:

print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### Exercise 35: How to compute ((A+B)*(-A/2)) in place (without copy)?
**Difficulty:** `★★☆`  
**Tags:** `In-place`

Given arrays A and B, evaluate `((A+B)*(-A/2))` modifying A and B directly using ufunc `out=` arguments.

**Expected Output:**
`Result stored directly in A`

<details>
<summary>💡 Hint</summary>

Use `np.add(A, B, out=B)`, `np.divide(A, 2, out=A)`, `np.negative(A, out=A)`, and `np.multiply(A, B, out=A)`.

</details>


In [7]:
# Exercise 35: How to compute ((A+B)*(-A/2)) in place (without copy)?
# Write your solution below:

A = np.arange(1, 5, dtype=float)
B = np.arange(6, 10, dtype=float)

np.add(A, B, out=B)
np.negative(A, out=A)
np.divide(A, 2, out=A)
np.multiply(B, A, out=A)

print(A)

[ -3.5  -9.  -16.5 -26. ]


### Exercise 36: Extract the integer part of a random array using 4 different methods
**Difficulty:** `★★☆`  
**Tags:** `Math`

Given a random array of positive floats, extract their integer parts using 4 distinct NumPy techniques.

**Expected Output:**
`Integer values`

<details>
<summary>💡 Hint</summary>

Try `Z - Z % 1`, `Z // 1`, `np.trunc(Z)`, and `Z.astype(int)`.

</details>


In [8]:
# Exercise 36: Extract the integer part of a random array using 4 different methods
# Write your solution below:

arr = np.random.default_rng().uniform(1, 10, 5)
print(arr)

print(arr.astype(int))
print(np.trunc(arr))
print(np.floor(arr))
print(arr // 1)
print(arr - arr % 1)

[4.93023452 6.35164434 7.46246236 6.54940267 9.67238002]
[4 6 7 6 9]
[4. 6. 7. 6. 9.]
[4. 6. 7. 6. 9.]
[4. 6. 7. 6. 9.]
[4. 6. 7. 6. 9.]


### Exercise 37: Create a 5x5 matrix with row values ranging from 0 to 4
**Difficulty:** `★☆☆`  
**Tags:** `Broadcasting`

Create a 5x5 matrix where each row is `[0, 1, 2, 3, 4]`.

**Expected Output:**
`5x5 matrix with rows 0 to 4`

<details>
<summary>💡 Hint</summary>

Add `np.arange(5)` to `np.zeros((5, 5))` using broadcasting.

</details>


In [25]:
# Exercise 37: Create a 5x5 matrix with row values ranging from 0 to 4
# Write your solution below:

matrix = np.zeros((5, 5), dtype=int) + np.arange(5)
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### Exercise 38: Build an array from a generator yielding 10 integers
**Difficulty:** `★☆☆`  
**Tags:** `Generators`

Define a Python generator that yields integers, and convert it to a NumPy array without creating an intermediate list.

**Expected Output:**
`Array of 10 integers`

<details>
<summary>💡 Hint</summary>

Use `np.fromiter(generator(), dtype=int, count=10)`.

</details>


In [41]:
# Exercise 38: Build an array from a generator yielding 10 integers
# Write your solution below:

def generate(n):
    for i in range(n):
        yield i

n = 10
print(np.fromiter(generate(n), dtype=int, count=n))


[0 1 2 3 4 5 6 7 8 9]


### Exercise 39: Create a vector of size 10 with values ranging from 0 to 1, both excluded
**Difficulty:** `★☆☆`  
**Tags:** `Linspace`

Generate 10 equally spaced values between 0 and 1, excluding 0.0 and 1.0.

**Expected Output:**
`10 values strictly inside (0, 1)`

<details>
<summary>💡 Hint</summary>

Use `np.linspace(0, 1, 11, endpoint=False)[1:]`.

</details>


In [94]:
# Exercise 39: Create a vector of size 10 with values ranging from 0 to 1, both excluded
# Write your solution below:

vector = np.linspace(0, 1, 11, endpoint=False)[1:]

print(vector)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### Exercise 40: Create a random vector of size 10 and sort it
**Difficulty:** `★☆☆`  
**Tags:** `Sorting`

Generate a 1D random vector of length 10 and sort it in ascending order.

**Expected Output:**
`Sorted array of 10 floats`

<details>
<summary>💡 Hint</summary>

Use `Z.sort()` or `np.sort(Z)`.

</details>


In [126]:
# Exercise 40: Create a random vector of size 10 and sort it
# Write your solution below:

vect = np.random.default_rng(seed=42).random(10)

print(np.sort(vect))

[0.09417735 0.12811363 0.43887844 0.45038594 0.69736803 0.7611397
 0.77395605 0.78606431 0.85859792 0.97562235]


### Exercise 41: How to sum a small array faster than np.sum?
**Difficulty:** `★★☆`  
**Tags:** `Performance`

Demonstrate how to compute the sum of a 1D array with lower function call overhead than `np.sum`.

**Expected Output:**
`Sum matching np.sum`

<details>
<summary>💡 Hint</summary>

Use the underlying ufunc reduction `np.add.reduce(Z)`.

</details>


In [133]:
# Exercise 41: How to sum a small array faster than np.sum?
# Write your solution below:

arr = np.arange(1, 10)

print(np.add.reduce(arr))  # Reduces overhead vs np.sum wrapper

45


### Exercise 42: Consider two random arrays A and B, check if they are equal
**Difficulty:** `★★☆`  
**Tags:** `Comparisons`

Check if two arrays A and B are equal: first for exact equality, then for floating-point tolerance.

**Expected Output:**
`Boolean True or False`

<details>
<summary>💡 Hint</summary>

Use `np.array_equal(A, B)` for exact match, and `np.allclose(A, B)` for tolerance.

</details>


In [757]:
# Exercise 42: Consider two random arrays A and B, check if they are equal
# Write your solution below:

A = np.random.default_rng().integers(0, 2, 4)
B = np.random.default_rng().integers(0, 2, 4)
print(A, B, sep="\n")

print(np.array_equal(A, B))  # Strict exact equality
print(np.allclose(A, B))  # Tolerance-based for floats

[1 0 1 0]
[1 0 1 0]
True
True


In [789]:
A = np.array([0.1 + 0.2])
B = np.array([0.3])
print(f"{A[0]:.17f}, {B[0]:.17f}")

print(np.array_equal(A, B))
print(np.allclose(A, B))

0.30000000000000004, 0.29999999999999999
False
True


### Exercise 43: Make an array immutable (read-only)
**Difficulty:** `★★☆`  
**Tags:** `Flags`

Modify an array's flags so that attempting to change any element raises an error.

**Expected Output:**
`Assignment raises ValueError`

<details>
<summary>💡 Hint</summary>

Set `Z.flags.writeable = False`.

</details>


In [ ]:
# Exercise 43: Make an array immutable (read-only)
# Write your solution below:

arr = np.array([1, 2, 3, 4, 5])

arr.flags.writeable = False  # Convert this array as immutable

# Try to add replace a value from this array
try:
    arr[2] = 6
except ValueError as e:
    print(e)


assignment destination is read-only


### Exercise 44: Convert a random 10x2 matrix representing cartesian coordinates to polar coordinates
**Difficulty:** `★★☆`  
**Tags:** `Trigonometry`

Given a 10x2 matrix of (X, Y) coordinates, compute radius R and angle Theta.

**Expected Output:**
`R and Theta arrays of length 10`

<details>
<summary>💡 Hint</summary>

Use `R = np.hypot(X, Y)` and `Theta = np.arctan2(Y, X)`.

</details>


In [834]:
# Exercise 44: Convert a random 10x2 matrix representing cartesian coordinates to polar coordinates
# Write your solution below:

matrix = np.random.default_rng().uniform(-10, 10, size=(10, 2))

X, Y = matrix[:, 0], matrix[:, 1]  # Seprating the array in X and Y varialbles

R = np.hypot(X, Y)  # To find the Radius (R) 

T = np.arctan2(Y, X)  # To find the Theta (Radian)

T_deg = np.degrees(T)  # If you need Theta transform to a Degree

print(np.column_stack((R, T)))  # The result (R, Theta) transform as a 10x2 matrix

[[ 4.45432551494848    1.604717420839629 ]
 [ 9.692586962739568  -0.835083046751752 ]
 [ 9.914292016111053   1.3119112063342588]
 [ 5.647986762764817   0.8478544638046394]
 [11.108618616181232   0.9850425832518114]
 [ 7.154562944424291   1.7387867123270515]
 [10.375186229373293   2.20437653940421  ]
 [12.235323018367039  -0.6793825803806136]
 [ 8.43745532247725   -1.113183012670753 ]
 [ 7.576582732011512  -3.04408337466627  ]]


### Exercise 45: Create random vector of size 10 and replace maximum value by 0
**Difficulty:** `★☆☆`  
**Tags:** `Argmax`

Find the maximum element in a random 1D array of size 10 and set its value to 0.

**Expected Output:**
`Array with maximum replaced by 0`

<details>
<summary>💡 Hint</summary>

Find the index with `Z.argmax()` and set `Z[Z.argmax()] = 0`.

</details>


In [ ]:
# Exercise 45: Create random vector of size 10 and replace maximum value by 0
# Write your solution below:

vect = np.random.default_rng().integers(1, 10, 10)
print(vect)

vect[vect == vect.max()] = 0  # Set all maximum values as a Zero 

print(vect)

[6 9 8 7 7 7 9 3 3 9]
[6 0 8 7 7 7 0 3 3 0]


In [883]:
vect = np.random.default_rng().integers(1, 10, 10)
print(vect)

print(np.where(vect == vect.max(), 0, vect))

[4 8 4 1 7 8 4 3 5 6]
[4 0 4 1 7 0 4 3 5 6]


In [886]:
vect = np.random.default_rng().integers(1, 10, 10)
print(vect)

vect[vect.argmax()] = 0  # Set first position maximum value as a Zero 

print(vect)

[1 3 1 3 7 2 8 8 6 2]
[1 3 1 3 7 2 0 8 6 2]
